### ISSUE TITLE
Minor typo in connectivity notifications

### ISSUE THREAD

**Issue by shahpiyushv** [CodorStelian/hm-io-connect-esp-rainmaker#1]
There's a missing space before "is" in the connectivity notifications. Screenshot for similar notifications in ESP RainMaker and IO Connect attached for reference.

![Screenshot_20210908-001202](https://user-images.githubusercontent.com/8659527/132395196-abfeb573-bfba-4939-b0e4-862b4efc000d.jpg)

**Comment by CodorStelian** [comment]
You're right, This is because I translated some strings. I will fix it in the next version update.
Thanks!
